### ISSUE TITLE
apt.so: cannot open shared object file

### ISSUE THREAD

**Issue by Babilinx** [Vanilla-OS/Vib#73]
I have installed `vib` inside a vanilla sub-system created in the GUI of `apx` using the instructions found here: https://docs.vanillaos.org/vib/en/getting-started#installation.

When I try to build a [modified](https://github.com/Babilinx/vanilla-minimal-desktop-image/tree/25bfe7316217f2a2c752b020ede311f2dd21e8ca) version of the desktop image with `vib build recipe.yml`, I get the following:
```
Building recipe Vanilla Desktop
Building module [init-setup] of type [shell]
Module [init-setup] built successfully
Building module [vanilla-tools] of type [shell]
Downloading source: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
Source is tar: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
Moving source: vanilla-tools
Module [vanilla-tools] built successfully
Building module [desktop-base] of type [dpkg-buildpackage]
Building module [desktop-base-deps-install] of type [apt]
Loading new plugin
panic: $INSTALLPREFIX$/share/vib/plugins/apt.so: cannot open shared object file: No such file or directory

goroutine 1 [running]:
github.com/vanilla-os/vib/core.LoadPlugin({0xc00012159c, 0x3}, {0x7cc7a0, 0xc00049d020}, 0xc000119180)
	/home/runner/work/Vib/Vib/core/plugins.go:37 +0x5a6
github.com/vanilla-os/vib/core.BuildModule(0xc000119180, {0x7cc7a0, 0xc00049d020})
	/home/runner/work/Vib/Vib/core/build.go:420 +0x2e5
github.com/vanilla-os/vib/core.BuildModule(0xc000119180, {0x7cc7a0, 0xc000111b60})
	/home/runner/work/Vib/Vib/core/build.go:400 +0x47d
github.com/vanilla-os/vib/core.BuildModules(0xc000119180, {0xc00011f208?, 0x242?, 0x1b6?})
	/home/runner/work/Vib/Vib/core/build.go:370 +0x115
github.com/vanilla-os/vib/core.BuildContainerfile(0xc000119180)
	/home/runner/work/Vib/Vib/core/build.go:80 +0x190
github.com/vanilla-os/vib/core.BuildRecipe({0x7fff43a0902c?, 0x0?})
	/home/runner/work/Vib/Vib/core/build.go:49 +0xdd
github.com/vanilla-os/vib/cmd.buildCommand(0xc000178100?, {0xc0001123a0?, 0x4?, 0x83170b?})
	/home/runner/work/Vib/Vib/cmd/build.go:80 +0x185
github.com/spf13/cobra.(*Command).execute(0xc000182308, {0xc000112360, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xb33c20)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/vanilla-os/vib/cmd.Execute(...)
	/home/runner/work/Vib/Vib/cmd/root.go:23
main.main()
	/home/runner/work/Vib/Vib/main.go:12 +0x1b
```

Vib version: `v0.7.4`
Apx version: `v2.4.3`
OS version: `Vanilla OS 2.0`

Note that the same thing is happening on the default vso-pico shell.

**Comment by axtloss** [comment]
those instructions are outdated, currently to install vib you have to clone this repo and run
```
make build
make build-plugins
sudo make install
sudo make install-plugins
```
this will install vib and the proper plugins in the container

**Comment by Babilinx** [comment]
Thank you.

But the Makefile is not right: for `sudo make install`, it wants `vib` to be on `./`, or it is in `build/`. Working fine for plugins.

```
install:
        install -Dm755 -t ${DESTDIR}/${PREFIX}/bin/ ./${BINARY_NAME}
```

**Comment by axtloss** [comment]
oh yeah
if you want to you can open a pull request to fix it

**Comment by Babilinx** [comment]
I'll do that :+1:

**Comment by Babilinx** [comment]
Hummm For some reasons I get the same message.
```
vib build recipe.yml 
Building recipe Vanilla Desktop
Building module [init-setup] of type [shell]
Module [init-setup] built successfully
Building module [vanilla-tools] of type [shell]
Downloading source: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
Source is tar: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
Moving source: vanilla-tools
Module [vanilla-tools] built successfully
Building module [desktop-base] of type [dpkg-buildpackage]
Building module [desktop-base-deps-install] of type [apt]
Loading new plugin
panic: $INSTALLPREFIX$/share/vib/plugins/apt.so: cannot open shared object file: No such file or directory

goroutine 1 [running]:
github.com/vanilla-os/vib/core.LoadPlugin({0xc00001566c, 0x3}, {0x7cc7c0, 0xc00059b9b0}, 0xc00010d180)
	/home/bastien/Vib/core/plugins.go:37 +0x5a6
github.com/vanilla-os/vib/core.BuildModule(0xc00010d180, {0x7cc7c0, 0xc00059b9b0})
	/home/bastien/Vib/core/build.go:420 +0x2e5
github.com/vanilla-os/vib/core.BuildModule(0xc00010d180, {0x7cc7c0, 0xc000017bf0})
	/home/bastien/Vib/core/build.go:400 +0x47d
github.com/vanilla-os/vib/core.BuildModules(0xc00010d180, {0xc000019688?, 0x242?, 0x1b6?})
	/home/bastien/Vib/core/build.go:370 +0x115
github.com/vanilla-os/vib/core.BuildContainerfile(0xc00010d180)
	/home/bastien/Vib/core/build.go:80 +0x190
github.com/vanilla-os/vib/core.BuildRecipe({0x7ffeb662603b?, 0x0?})
	/home/bastien/Vib/core/build.go:49 +0xdd
github.com/vanilla-os/vib/cmd.buildCommand(0xc000148100?, {0xc00002e400?, 0x4?, 0x83174b?})
	/home/bastien/Vib/cmd/build.go:80 +0x185
github.com/spf13/cobra.(*Command).execute(0xc000152308, {0xc00002e3c0, 0x1, 0x1})
	/home/bastien/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xb30c40)
	/home/bastien/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/bastien/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/vanilla-os/vib/cmd.Execute(...)
	/home/bastien/Vib/cmd/root.go:23
main.main()
	/home/bastien/Vib/main.go:12 +0x1b
```

And

```
$ ls /usr/share/vib/plugins/       
apt.so  cmake.so  dpkg-buildpackage.so  go.so  make.so  meson.so
```

**Comment by Babilinx** [comment]
I think I get it.

In plugins.go: https://github.com/Vanilla-OS/Vib/blob/main/core/plugins.in#L29 => `$INSTALLPREFIX$`
But `sed` in the Makefile search for `$$INSTALLPREFIX$$`.

**Comment by axtloss** [comment]
oh yeah i have that fixed locally already, it'll be pushed later

**Comment by axtloss** [comment]
for now you can put the plugins in the `plugins` directory of the project itself

**Comment by Babilinx** [comment]
Okey, thanks!
